# Generated by Django 4.1.1 on 2022-12-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categories',
            new_name='categories',
        ),
    ]
